version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: wallet_service_db
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - wallet_data:/var/lib/postgresql/data
volumes:
  wallet_data: